services:
  web:
    image: denoland/deno:2.2.3
    env_file:
      - path: ./env/web.env
    ports:
      - 8000:8000
    working_dir: /app
    command: >
      sh -c "deno task start"
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_started
  postgres:
    image: postgres:17.4
    ports:
      - 5432:5432
    environment:
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: VkoJeNJyoPXpUbnRYNwvAnriFh
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh:ro
volumes:
  pgdata:
